//User actionTypes
export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";

// Post actionTypes
export const FETCH_POST_DATA_REQUEST = "FETCH_POST_DATA_REQUEST";
export const FETCH_POST_DATA_SUCCESS = "FETCH_POST_DATA_SUCCESS";
export const FETCH_POST_DATA_FAIL = "FETCH_POST_DATA_FAIL";
export const FETCH_SINGLE_POST_REQUEST = "FETCH_SINGLE_POST_REQUEST";
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";
export const FETCH_SINGLE_POST_FAIL = "FETCH_SINGLE_POST_FAIL";

//Channel actionTypes
export const FETCH_CHANNEL_DATA_REQUEST = "FETCH_CHANNEL_DATA_REQUEST";
export const FETCH_CHANNEL_DATA_SUCCESS = "FETCH_CHANNEL_DATA_SUCCESS";
export const FETCH_CHANNEL_DATA_FAIL = "FETCH_CHANNEL_DATA_FAIL";
